build:
	docker build -t m4ri .
run:
	docker run --it --rm --name m4ri m4ri
#	docker run -it --rm -v `pwd`/workspace:/root/workspace -p 0.0.0.0:8888:8888 -p 0.0.0.0:8889:22 -p 0.0.0.0:8890:8890 -p 0.0.0.0:8891:80 --name ubuntu-full ubuntu-full
